apiVersion: apps/v1
kind: Deployment
metadata:
  name: hf-infer
spec:
  replicas: 1
  strategy:
   type: Recreate
  selector:
    matchLabels:
      app: hf-infer
  template:
    metadata:
      labels:
        app: hf-infer
    spec:
      containers:
        - name: api
          image: saujandsre/hf-gpu-infer:min
          imagePullPolicy: IfNotPresent
          env:
            - name: MODEL_PATH
              valueFrom:
                configMapKeyRef:
                  name: hf-config
                  key: MODEL_PATH
          ports:
            - containerPort: 8000
          resources:
            requests:
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1

