apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-demo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: rke2-server
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ml-demo-svc
            port:
              number: 80
